{% set name = "tensorboardX" %}
{% set version = "2.6.4" %}
{% set sha256 = "b163ccb7798b31100b9f5fa4d6bc22dad362d7065c2f24b51e50731adde86828" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tensorboardX/tensorboardx-2.6.4.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools-scm
    - setuptools >=42
    - wheel
  run:
    - python
    - numpy
    - packaging
    - protobuf >=3.20

test:
  imports:
    - tensorboardX
    - tensorboardX.crc32c
    - tensorboardX.embedding
    - tensorboardX.event_file_writer
    - tensorboardX.onnx_graph
    - tensorboardX.record_writer
    - tensorboardX.summary
    - tensorboardX.writer
    - tensorboardX.x2num
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lanpa/tensorboardx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tensorboard for pytorch
  description: |
    Write tensorboard events from PyTorch (and Chainer, MXNet, NumPy, ...)
  doc_url: https://tensorboardx.readthedocs.io
  dev_url: https://github.com/lanpa/tensorboardx

extra:
  recipe-maintainers:
    - mdraw
    - lanpa
