{% set name = "tensorboardX" %}
{% set version = "1.7" %}
{% set sha256 = "f920d43cbe24c631fff94c89aad8f4568fe310e11f889cce4aadfa1760ebb85c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - protobuf >=3.2.0
    - six

test:
  imports:
    - tensorboardX
    - tensorboardX.crc32c
    - tensorboardX.embedding
    - tensorboardX.event_file_writer
    - tensorboardX.onnx_graph
    - tensorboardX.record_writer
    - tensorboardX.summary
    - tensorboardX.writer
    - tensorboardX.x2num

about:
  home: https://github.com/lanpa/tensorboardx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tensorboard for pytorch

  description: |
    Write tensorboard events from PyTorch (and Chainer, MXNet, NumPy, ...)
  doc_url: https://tensorboardx.readthedocs.io/en/latest/
  dev_url: https://github.com/lanpa/tensorboardx

extra:
  recipe-maintainers:
    - mdraw
    - lanpa
