{% set name = "tensorboardx" %}
{% set version = "1.0" %}
{% set sha256 = "33d761b902dd3a3bc9b48d1a5921f6ee99878e612385e52826c12438c99741fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lanpa/tensorboard-pytorch/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - protobuf >=0.3.2
    - six

test:
  imports:
    - tensorboardX
    - tensorboardX.crc32c
    - tensorboardX.embedding
    - tensorboardX.event_file_writer
    - tensorboardX.graph
    - tensorboardX.graph_onnx
    - tensorboardX.record_writer
    - tensorboardX.summary
    - tensorboardX.writer
    - tensorboardX.x2num

about:
  home: https://github.com/lanpa/tensorboard-pytorch
  license: MIT
  license_family: MIT
  summary: tensorboard for pytorch

  description: |
    Write tensorboard events from PyTorch (and Chainer, MXNet, NumPy, ...)
  doc_url: http://tensorboard-pytorch.readthedocs.io/en/latest/
  dev_url: https://github.com/lanpa/tensorboard-pytorch

extra:
  recipe-maintainers:
    - mdraw
    - lanpa
