travis:
  secure:
    BINSTAR_TOKEN: P+/zzDWXf6pkLbzHurvIrk11sWFULmYaC7pt4YuMIYIj66lHOqhnDyaVDD1Z0wZd3j0UNzw/FWmenRNMuVPsaOmItYELcvt2hiN4wEo/XAV5vuE99qNKeTT2TU267dRYT3a27LndmZRgFTMeK771/yV1EF4InMIwfnIKeBA9TAPPB7qD6n2COG93lP3HhFo+msTqicujRb9wmtq8FmeccQRlrIrfMroZ3EGoSwMpQlJskCZi+vC9qHK2NRCn8NxqWD+sc6a30grtSWNbP8p2WvGLPJ5i4IDVhqYCZfMd6gssE/z4zcNFL9+o/Eb/6C9YENK1LVyPtRkIPzOCIUyOizHU9KNwnsOesrmA0gQSt3dInsYfluaG22jIRzJmILJjRcbT/qPfDJ/Qbp+9QIV9VCkyytCQFDNiSIGbRfNspUzU5gM4Zlxyg8M0oCxT54qaoZ5azWyqTvIvnNI3vA303YiM5zYW49hMuwta7h+dlk6SJD6VSqIqvfxAoNyWUbMovlMvRyCaWOJjREOTQXYubF/amsNf12Mhph0eTGQexNGDUOvpe5K4OliTY4n7jCsuOj/Fu41F/rvdO1n0/iEfN4VdxelsbM0JV+CSgcwBLhEWA3AotJcgMkH/icPEEHOrVGUcikVGquDtsemxAXZZwy1LFKSrZuOBfj2w1+N8MT8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
