travis:
  secure:
    BINSTAR_TOKEN: Grzc6fJpObQs2PENjj5oCyY0IA5eLg1hDJdwhL07bZx1jcFYabDPQf9YCCYsKQGYVhEsoXM1KHXzJlVNlKgIPqiWE2/gPo5ehohhKJHmNpoWdsZCAuMVlXFCNQY69p+m5qJV56IC+Qdj97fAERNO7t23u6JAh7SIil3DFYj7Tq0++JImQgbZZc172MEWz+bWDTAJQ+SrgtJMswgFVyBhO1n+NXtYEn28QXxN3H01SKMvgQsif7am9E/OrcvPbNJKR9C32ycbSwFkdbRICkRtxjTfeFDtcInR3JYkG8xmJvwjAfLTf1hLltFTIUEYkN3GAP/j2j614q1aWNKtwtcdlehH3lUXg683lCFkB+KFQMqCunxGfgveENUgSwZIe5CQOpZmD0XIVStr9NxbQSHWP4X+TUBtGDuvyIOmdyDh9VxHSSOO2e6h+PpEpQEzlenTCO0TPfq2apoYBNJp+BgADCcSAUuwVT8sPoxiazAM4FAWHaKtql88xfGCeBr3glrymkyis/pmUEXhzfSAwcfA6gEBRrUP5cG+ucrPEnxtPbY03ort7WwiXFZVR21rllvPiuR8ntfXQrDrVpaxlPituBnu73dnQmG7cODOWLvB1m2kAYExzJp9GCboinQPrNbdR1J80Fikc3zt9aGzJnHBN/398P5tgaTn6fDOFVTwF5s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
