travis:
  secure:
    BINSTAR_TOKEN: MOlUo+2+Y+InFSicFn7CMus+CcxmmLPMbBG7AexvBbbATC6S8SS7jqP1quuZ4G9cgSGn2JNqk5hsuA23F2C6jvmgGdPss4xQ0IO5lG984GfpekUt5HQf2758mHRM2Bq7T3Yt/qozLLPLjax9OP8P5GWLwhCriLZXQWc3SLaBIQVYvT3xIyD5MX6UIg3o8yn3WuhxrttqqoiJIXLhmCgmyt0tob8T5YOFeK8NdsrD0RyW/Ht2vvHaTjA3nZa0C2k+Ig7et6EKNv9XrzjlRh7JKIZrIMWTrXg2dwMErFHzuckTJPwSWj5NXgW9GHD97D+FnuK0+wywo6WetyYVBmP0h3ItmLCJDezvEXi1nSxvfgUuwwclXTixczk/II4D1iOWsLaM3DRz0tkoWmqrVKNZ3L6xA2kZf8A1wgnFbl+b5gr4AatcecDDYLQKbVKaA3oLmmWxWyPUYC+dgiJevwvAjwQNRktkQI0m89T0xEZSdaKnjkxUuHTDSScQeoeJobwOOMwLxMFgDT5NnqFwqlhQWwb0muGA67Yxv22NrfIt8aPiLGWmK3p7bE2S0J+UfFsg50SQZf4omr/4Ouyo1XamGJqEsPHXzbVtKhWsuMaXHTgGlYmT5IofHsgQij8w1oKPykKCcpDw7ZGxlEY2hSj2WnBSvCz5CiusJ/F885oEU5A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
